<<<<<<< HEAD
# Site settings
title: 어쩌다보니 개발자
email: kis6905@gmail.com
description: #1leaf #개발 #블로그
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: kis6905
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/kis6905/kis6905.github.io
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/kis6905/kis6905.github.io
#########################################
# for duoshuo.com commenting system, uncomment following line if you do not want to include duoshuo.com. 
#duoshuo_shortname: lixizhi
#duoshuo_url: "http://lixizhi.github.io"
# disqus.com commenting system. please note that it is exclusive with duoshuo.com
disqus_shortname: 1leaf
disqus_url: "https://github.com/kis6905/"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
=======
theme: jekyll-theme-cayman
>>>>>>> 48d6f411d8ffc685f85146f96a8a7ffb6d3a1a5b
